function(generate_input_class GeneratedFiles OutputDir)
	if (NOT ${CUSTOM_PYTHON})
		find_package(PythonInterp REQUIRED)
	else()
		set (PYTHON_EXECUTABLE ${CPYTHON_EXECUTABLE})
	endif()
	file (GLOB INPUTFILES resources/inputs/*.json)
	foreach (jsonFile ${INPUTFILES})
		execute_process(COMMAND ${PYTHON_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/resources/inputs/inputclassgenerator.py -i ${jsonFile} -o ${OutputDir})
	endforeach(jsonFile)
	file(GLOB files ${OutputDir}/*)
	set (${GeneratedFiles} ${files} PARENT_SCOPE)
endfunction()