mapClassHeaderFile = """#include "input/abstractactionmap.h"
/*
    This file is automatically generated through Python script "inputclassgenerator.py"
    that can be seen in resources files, and that is called during the build of the project
    by Cmake. Please, do not modify them.
*/
class ${NAME}ActionMap : public AbstractActionMap
{
public:
    ${NAME}ActionMap();
    ${ACTIONS_NAMES}
private:
    ${ACTIONS_SETUP_FUNCTIONS_DECLARATION}
};
"""

mapClassFileName= "${NAME}actionmap"

mapClassSourceFile = """#include "${GENERATED_HEADER_MAP_FILENAME}.h"
#include "input/binding.h"

${NAME}ActionMap::${NAME}ActionMap(): ${ACTIONS_INIT}
{
    ${ACTIONS_SETUP_FUNCTION_CALLING}
}

${ACTION_SETUP_FUNCTION_DEFINITION}
"""

mapClassActionSetupTemplate = """
void ${NAME}ActionMap::${ACTION_NAME}Setup()
{
    ${ACTION_BINDINGS}
    m_actions.push_back(&${ACTION_NAME});
}
"""

bindingDeclaration = "new ${TYPE}Binding(${PARAM});"

controlSchemeHeaderFile = """
#include "input/abstractcontrolscheme.h"
${ACTION_MAP_INCLUDES}

class ${NAME} : public AbstractControlScheme
{
public:
    ${NAME}();

    ${ACTION_MAPS}
};
"""

controlSchemeSourceFile = """#include "${HEADER_FILE_NAME}.h"

${CLASSNAME}::${CLASSNAME}()
{
    ${ADD_ACTION_MAPS}
}

"""

